task_processor:
  worker_threads: 4

server:
  listener:
    port: 8080
    task_processor: main-task-processor

components:
  in-memory-storage: {}
  
  jwt-auth-checker-component:
    secret-key: "${JWT_SECRET_KEY:default-secret-key}"
  
  handler-auth-login:
    path: /api/v1/auth/login
    method: POST
    
  handler-user-create:
    path: /api/v1/users
    method: POST
    
  handler-user-search:
    path: /api/v1/users/search
    method: GET
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-user-get-by-login:
    path: /api/v1/users/login/{login}
    method: GET
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-patient-create:
    path: /api/v1/patients
    method: POST
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-patient-search:
    path: /api/v1/patients/search
    method: GET
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-record-create:
    path: /api/v1/records
    method: POST
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-patient-records:
    path: /api/v1/patients/{patient_id}/records
    method: GET
    auth:
      types:
        - jwt-auth-checker-component
    
  handler-record-by-code:
    path: /api/v1/records/{code}
    method: GET
    auth:
      types:
        - jwt-auth-checker-component

logger:
  file_path: '@stderr'
  level: info
